name: HeliSolutions
favicon: null
layout_spectrum: 0.3741696758661419
typography_spectrum: 0.1026599386241287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7523811236023903
  lightness: 0.2751418789848685
  saturation: 0.6826642889063805
  rhythmicContrast: 0.37705534836277366
purpose: []
